version: "3.9"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  lab:
    build: .
    volumes:
      - ./clustering.ipynb:/home/lab
    labels:
      caddy: lab.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8888}}"
      traefik.enable: "true"
      traefik.http.routers.lab.rule: Host(`lab.marcpartensky.com`)
      traefik.http.routers.lab.entrypoints: websecure
      traefik.http.routers.lab.tls.certresolver: tls
      traefik.http.services.lab.loadbalancer.server.port: 8888
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.lab.rule: Host(`lab.marcpartensky.com`)
        traefik.http.routers.lab.entrypoints: websecure
        traefik.http.routers.lab.tls.certresolver: tls
        traefik.http.services.lab.loadbalancer.server.port: 8888


volumes:
  postgres:
