version: "3.9"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  lab:
    build: .
    volumes:
      - ./clustering.ipynb:/home/lab


volumes:
  postgres:
