version: "3.9"
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5433:5432"
    networks:
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  lab:
    image: marcpartensky/frhack-lab
    build: .
    volumes:
      - ./clustering.ipynb:/home/lab/clustering.ipynb
      - ./prep:/home/lab/prep
    networks:
      - caddy
    labels:
      caddy: lab.marcpartensky.com
      caddy.reverse_proxy: "{{upstreams 8888}}"
      traefik.enable: "true"
      traefik.http.routers.lab.rule: Host(`lab.marcpartensky.com`)
      traefik.http.routers.lab.entrypoints: websecure
      traefik.http.routers.lab.tls.certresolver: tls
      traefik.http.services.lab.loadbalancer.server.port: 8888
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.lab.rule: Host(`lab.marcpartensky.com`)
        traefik.http.routers.lab.entrypoints: websecure
        traefik.http.routers.lab.tls.certresolver: tls
        traefik.http.services.lab.loadbalancer.server.port: 8888

  pgweb_frhack:
    image: sosedoff/pgweb
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password
    networks:
      - postgres
      - caddy
    depends_on:
      - postgres
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.pgweb_frhack.rule: Host(`db.frhack.marcpartensky.com`)
        traefik.http.routers.pgweb_frhack.entrypoints: websecure
        traefik.http.routers.pgweb_frhack.tls.certresolver: tls
        traefik.http.services.pgweb_frhack.loadbalancer.server.port: 8081
        # ldapAuth Register Middleware ====================================================
        # traefik.http.routers.pgweb.middlewares: ldap_auth

volumes:
  postgres:
networks:
  postgres:
  caddy:
    external: true
