version: "3.9"
services:
  postgres_db:
    image: postgres:9.6-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:user}
      POSTGRES_DB: ${POSTGRES_DB:db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:password}
