global:
  checkNewVersion: true
  sendAnonymousUsage: false
api:
  # insecure: false # = secure
  insecure: true
  dashboard: true
  debug: true
providers:
  docker:
    swarmMode: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # traefik enabled containers only
    network: web
  file:
    filename: dynamic.yml
certificatesResolvers:
  tls:
    acme:
      tlsChallenge: {}
      email: marc.partensky@gmail.com
      storage: /letsencrypt/acme.json
ping: {} # mandatory for healthcheck
log:
  level: debug
  # level: error
entryPoints:
  websecure:
    address: ':443'
    forwardedHeaders:
      insecure: true
      # http3:
      #   advertisedPort: 443
    http:
      tls:
        certResolver: tls
      # middlewares:
      #   - ldap
    # http3:
    #   advertisedPort: 443
  web:
    address: ':80'
    forwardedHeaders:
      insecure: true
    # forwardedHeaders:
    #   trustedIPs:
    #     - "127.0.0.1/32"
    #     - "192.168.1.7"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
          priority: 10
